### ISSUE TITLE
Front Page Logo

### ISSUE THREAD

**Issue by alexsb** [utah-datascience/utah-datascience.github.io#13]
The Logo could be more prominent; see utah.edu or vdl.sci.utah.edu for examples. This could be only for the front page, but  possibly for all pages.

**Comment by jrogerthat** [comment]
![Screen Shot 2020-02-14 at 9 54 02 AM](https://user-images.githubusercontent.com/22663748/74551239-11819f00-4f10-11ea-857b-8894db2d630e.png)
made the logo a little bigger - does this seem like a better size? (working on removing title below)

**Comment by alexsb** [comment]
I think this works! Closing.
