### ISSUE TITLE
Title text on member page

### ISSUE THREAD

**Issue by alexsb** [utah-datascience/utah-datascience.github.io#9]
This text here is hard to read. I don't think this works in front of an image and without alignment. 

![image](https://user-images.githubusercontent.com/2039375/74284037-3a235200-4ce0-11ea-9c48-de11b59e4260.png)

I'd suggest to put this at the bottom; this isn't all that interesting; and show it on white background.

**Comment by jrogerthat** [comment]
<img width="1467" alt="Screen Shot 2020-02-11 at 6 42 02 PM 1" src="https://user-images.githubusercontent.com/22663748/74295546-92694c80-4cfe-11ea-9190-eefd720be556.png">

Hey Alex I did some rearranging - what do you think about moving it to the top?

**Comment by alexsb** [comment]
It's better visually, but I don't think it's that important, so from a logical point of view, it should go to the bottom IMO.
